# Generated by Django 5.0.6 on 2024-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('description', models.TextField(verbose_name='Опис')),
                ('rating', models.IntegerField(choices=[(1, '1 - Дуже погпно'), (2, '2 - Погано'), (3, '3 - Пройде'), (4, '4 - Добре'), (5, '5 - Дуже добре')], verbose_name='Рейтинг')),
                ('is_positive', models.BooleanField(verbose_name='Positive Review')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Image')),
            ],
        ),
    ]
